name: Build and publish release
# TODO implement take version from pyproject.toml
on:
  release:

jobs:
  build-image:
    runs-on: ubuntu-latest
    env:
      INPUT_RETRIEVER_PROJECT: ${{ toLower(github.event.repository.name) }}-input-retriever
      RAO_PROJECT: ${{ toLower(github.event.repository.name) }}-rao
    steps:
      - uses: actions/checkout@v4

      - name: Set Variables
        run: |
          echo "INPUT_RETRIEVER_PROJECT=$(basename "$GITHUB_REPOSITORY" | tr '[:upper:]' '[:lower:]')-input-retriever" >> $GITHUB_ENV
          echo "RAO_PROJECT=$(basename "$GITHUB_REPOSITORY" | tr '[:upper:]' '[:lower:]')-rao" >> $GITHUB_ENV
          echo "IMAGE_TAG=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV
          echo "LATEST_TAG=latest" >> $GITHUB_ENV

      - uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v5
        with:
          context: .
          file: input_retriever/Dockerfile
          push: true
          tags: |
            ${{ vars.DOCKER_USERNAME }}/${{ env.INPUT_RETRIEVER_PROJECT }}:${{ env.IMAGE_TAG }}
            ${{ vars.DOCKER_USERNAME }}/${{ env.INPUT_RETRIEVER_PROJECT }}:${{ env.LATEST_TAG }}
            
      - uses: docker/build-push-action@v5
        with:
          context: .
          file: rao/Dockerfile
          push: true
          tags: |
            ${{ vars.DOCKER_USERNAME }}/${{ env.RAO_PROJECT }}:${{ env.IMAGE_TAG }}
            ${{ vars.DOCKER_USERNAME }}/${{ env.RAO_PROJECT }}:${{ env.LATEST_TAG }}
